### ISSUE TITLE
@username autofill eats the proceeding text 

### ISSUE THREAD

**Issue by odetomyday** [Gargron/mastodon#193] opened 2016-11-22 15:07 UTC
When there is text already after the @, the autofill replaces however many characters ahead. See photo. 

![gargon bug](https://cloud.githubusercontent.com/assets/17036185/20528761/6e3f2968-b09b-11e6-8136-1fb7f0ca4fcb.png)

**Comment by Gargron** [comment] 2016-12-08 18:12
Duplicate of #156, track progress there

**Closed by Gargron** 2016-12-08 18:12 UTC
Labels: bug
