### ISSUE TITLE
Mobile profile view has no room for toots

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#257] opened 2016-11-24 16:44 UTC
For example: https://mastodon.social/media/13730

Twitter app's behavior in this instance is to make the profile scroll out.

**Comment by unsmell** [comment] 2016-11-24 17:07
here's a screenshot for reference
![screenshot_20161124-160641](https://cloud.githubusercontent.com/assets/2267475/20606378/0c4f67a6-b260-11e6-80fd-b6b0e9b42aa4.png)

**Comment by Gargron** [comment] 2016-11-24 17:52
Ideally we need more Responsive Design :tm: but I'm a terrible person who uses inline styles in React.js so fml

**Comment by Gargron** [comment] 2016-12-08 18:10
Duplicate of #196, track progress there

**Closed by Gargron** 2016-12-08 18:10 UTC
Labels: enhancement
