### ISSUE TITLE
If a post is boosted then un-boosted, the post will disappear out of the activity stream

### ISSUE THREAD

**Issue by mcat-ee** [Gargron/mastodon#377] opened 2016-12-30 16:29 UTC
(See title)

This happens even if it's my post to start with; is this expected behaviour?

**Comment by Gargron** [comment] 2016-12-30 18:18
Duplicate of #147 which I still haven't resolved because everyone wanted me to work on something else. I'll update the older issue when something about this situation changes

**Closed by Gargron** 2016-12-30 18:18 UTC
