### ISSUE TITLE
Interactivity improvements to the stand-alone toot page

### ISSUE THREAD

**Issue by paralithode** [Gargron/mastodon#326] opened 2016-12-01 11:19 UTC
When opening a toot in a new tab, the page (for instance https://mastodon.social/users/paralithode/updates/304032 ) has no options to interact with the content. There's no ability to boop, boost or reply. If, for instance, you open an interesting toot meaning to interact with it later, actually doing so becomes quite circuitous. In effect you have to track down the post manually through the main interface. I think this makes a higher barrier to entry for free-flowing interaction.

Being able to use individual post pages to chain new replies might also add flexibility to how we use mastodon. E.g you could follow the main public timeline on your regular mastodon page, chatting away, and keep track of a few more in-depth ongoing conversations in their own tabs. 

I think this is somewhat related to issue #324 because public profile & single toot links seem to have the same conceptual issue – they exist isolated from the interactive flow of the community due to a late of re-entry points.

This is my first github issue, how did I do? I had a look around and I haven't spotted this being raised before, apologies if this is a clone!

**Comment by TazeTSchnitzel** [comment] 2016-12-01 17:34
This is essentially a duplicate of https://github.com/Gargron/mastodon/issues/174, or of https://github.com/Gargron/mastodon/issues/216, which is itself a duplicate of the former.

**Comment by swaldie** [comment] 2016-12-05 20:59
As @TazeTSchnitzel mentioned earlier, this is a duplicate of #174.  Please check #174 for updates on this issue.  Thank you.

**Closed by swaldie** 2016-12-05 20:59 UTC
Labels: duplicate
